export const VOCAB_EN = {
  products:'Products',
  collections: 'Collections',
  goldschemes:'Gold Schemes',
  aboutus:'About Us',
  contactus: 'Contact Us',
  
  our: 'our',
  
  wedding: 'wedding',
  men: 'men',
  women: 'women',
  kids: 'kids',
  gifts:'gifts',
  
  
  gold: 'gold',
  diamond:'diamond',
  silver: 'silver',
  promises: 'Promises',
  top: 'top',
  sellingjewels: 'selling jewels',
  whatpeople: 'What People',
  talkaboutus:'talk about us',
  talktous: 'talk to us',
  todaysrate: 'Today\'s Rate',
  
  findyourjewels: 'find your jewels',
  necklace: 'necklace',
  allproducts: 'all products',
  maalai: 'maalai',
  bangles: 'bangles',
  chains: 'chains',
  earrings: 'earrings',
  rings: 'rings',
  bracelet: 'bracelet',
  stud:'stud',

  Maalai: 'maalai',
  Bangles: 'bangles',
  Chains: 'chains',
  Earrings: 'earrings',
  Rings: 'rings',
  Bracelet: 'bracelet',
  Necklace: 'necklace',
  Stud: 'stud',
  Dollar: 'dollar',
  Anklet: 'anklet',
  Gifts:'gifts',
  //have to translate
  goldsavingscheme:'gold saving scheme',
  goldschemedata: 'Investing in gold has never been easier, SBJ Gold scheme is a special scheme that helps you to plan and buy your own dream jewellery as well as maintaining your healthy financial stability. We have two options specially designed to suit your individual levels of saving at your own pace. You will also be rewarded with a special prize when you subscribe to one of our gold schemes.',
  flexischemeHead: 'FLEXIBLE MONEY SCHEME',
  flexip1: 'Under this scheme, You will be able to invest money, which will be credited as cash in your account and the premium by the end of 11th month, will be provided to you with a month bonus.',
  flexip2: 'The current gold cost on the day of purchase will be taken into account when we buy gold with this gold scheme. The gold you purchase will be subject to gold making and wastage charge*.',
  flexip3: 'Note: Under this scheme, you won\'t be able to withdraw the premium as cash, the money which is available in your account only be used to buy gold based on that particular day gold rate',
  downloadhere: 'Download Brochure',
  happyGoldHead: 'HAPPY GOLD SCHEME',
  happyGold1: 'With this scheme, Your money will be invested at the current gold rate and will be accumlated as gold weight rather than cash in your account. ',
  happyGold2: 'By the end of the 11th month, you will be able to buy gold corresponding to the accumulated weight without any making and wastage charges*.',
  happyGold3: '*- Taxes Apply at 3% ',
  termshead: 'Terms and Conditions',
  termsbody1: 'The premium due amount can be paid on any day of the month.',
  termsbody2: 'The savings tenure is 11 months only.',
  termsbody3: 'The premium amount can also be paid through NEFT ( Bank account details are given below )',
  termsbody4: 'while depositing the premium amount though NEFT , do not forget to mention the customer identification number as well as the name of the customer with whom the gold scheme is registered.',
  termsbody5: 'After depositing the amount through bank , kinldy call our customer call number and inform them regarding the transfer.',
  termsbody6: 'The gold scheme once registered is not transferable and the entire gold scheme package cannot be transfered to the other person.',
  termsbody7: 'The gold scheme cannot be closed before the tenure. kinldy bring the gold scheme card while depositing the premium amount directly through cash.',
  termsbody8: 'The premium due amount can be paid on any day of the month. kindly bring the customer registration card when buying the gold corresponding to the premium amount After the tenure completes.',
  termsbody9: 'All the " Happy Gold " customers will be able to buy the gold coressponding to the premium amount with any gold making and wastage charge.',
  termsbody10: 'Taxes Application ( Current GST 3 % ).',
  termsbody11: ' The store has the full privilege to modify / change the above terms and conditions.',
  locations:'locations',
  storename1: 'Sri Balagopalan Jewellery Mart',
  storename2: 'Sri Silver',
  goldstore: 'Gold Store',
  address: 'Address',
  addressbody1: `No.2, Jansi Rani Complex ,\n YMCA Building Opposite, Madurai – 625 001.`,
  buisnesshours: 'Buisness Hours',
  buisnesshoursbody1: 'Every Day 9AM - 9PM',
  phonenumber: 'Phone Number',
  phonenumberbody1: '+91-99949-26518',
  phonebody1: '9994926518',
  phonenumberbody2: '+91-452-2346518',
  silverstore: 'Exclusive Store for Silver',
  addressbody2: '218, West Masi Street Madurai-625001',
  phonenumberbody3: '+91-95854-42214',
  phonenumberbody4: '0452-4393919',
  get: 'Get',
  intouch: 'in touch',
  fullname: 'Full Name',
  email: 'Email',
  subject: 'Subject',
  message: 'Message',
  enter: 'Enter Your ',
  send: 'Send ',
  connect: 'Connect',
  withus: 'with us',
  allcollections:'All Collections',
  marriage: 'wedding',
  story:'story',
  aboutusdata1:'In 1992, Sri Balagopalan Jewellery Mart has been inaugrated in Small Scale by S.B.Senthilkumar . Each and everyone feel elite on shopping with us in quality, design, price and service . Quality for the end consumer is key priority for us and we are comitted to fulfill our promises!!!',
  Gold: 'gold',
  Diamond:'diamond',
  Silver: 'silver',
  talktoushome: 'Have questions about our exquisite jewellery collections and can\'t decide what suits your taste! Look no further',
  talktousgold: 'Confused with the gold collection you are looking at? Leave it to us',
  talktousdiamond: 'Confused with the Diamond collection you are looking at? Leave it to us',
  talktoussilver: 'Confused with the Silver collection you are looking at? Leave it to us',
  talktousproduct: 'Can\'t decide between our products? We\'ll make sure that is not a problem, reach out to us',
  talktouscollection: 'Not convinced of our displayed collection here? This is just a tip of iceberg with our collections available at our store, contact us for more info ',
  talktousgoldscheme: ' Not planning to buy gold yet? Invest in our gold scheme to make the most out of your saving. ',
  promise1: 'Certified Pure Gold',
  promise2: 'All Jewels are brand new',
  promise3: 'Transparency in pricing',
  promise4:'Secure Gold Scheme',
 

  dollar: 'dollar',
  anklet: 'anklet',
  noproductsfound: 'No Products Found',
  fillallfields: 'Please fill all the fields',
  close: 'close',


  silvervessels: 'Vessels',
  idols:'idols',
  poojaitems: 'Pooja Items',
  
  goldheroline1:  'Get ready to explore the wide spectrum of',   
  goldheroline2:'creativity and style with our Gold ornaments',
  diamondheroline1:  'let the jewellery make your life',
  diamondheroline2: 'bright and shine with exquisite Diamonds',
  silverheroline1:'lustrous and shinny aura, Silver jewellery ..',
  collectionsheroline1: 'Look as beautiful outside as you are within',
  collectionsheroline2:  'through our enormus collections ...'          
  
}