export const VOCAB_EN = {
  products:'Products',
  collections: 'Collections',
  goldschemes:'Gold Schemes',
  aboutus:'About Us',
  contactus: 'Contact Us',
  
  our: 'our',
  
  wedding: 'wedding',
  men: 'men',
  women: 'women',
  kids: 'kids',
  gifts:'gifts',
  
  
  gold: 'gold',
  golda: 'gold',
  diamond:'diamond',
  silver: 'silver',
  promises: 'Promises',
  top: 'top',
  sellingjewels: 'selling jewels',
  whatpeople: 'What People',
  talkaboutus:'talk about us',
  talktous: 'talk to us',
  talkto: 'talk to',
  us:'us',
  todaysrate: 'Today\'s Rate',
  
  findyourjewels: 'find your jewels',
  necklace: 'necklace',
  allproducts: 'all products',
  maalai: 'maalai',
  bangles: 'bangles',
  chains: 'chains',
  earrings: 'earrings',
  rings: 'rings',
  bracelet: 'bracelet',
  stud:'stud',

  Maalai: 'maalai',
  Bangles: 'bangles',
  Chains: 'chains',
  Earrings: 'earrings',
  Rings: 'rings',
  Bracelet: 'bracelet',
  Necklace: 'necklace',
  Stud: 'stud',
  Dollar: 'dollar',
  Anklet: 'anklet',
  Gifts:'gifts',
  //have to translate
  goldsavingscheme:'gold saving scheme',
  goldschemedata: 'Investing in gold has never been easier, SBJ Gold scheme is a special scheme that helps you to plan and buy your own dream jewellery as well as maintaining your healthy financial stability. We have two options specially designed to suit your individual levels of saving at your own pace. You will also be rewarded with a special prize when you subscribe to one of our gold schemes.',
  flexischemeHead: 'FLEXIBLE MONEY SCHEME',
  flexip1: 'Under this scheme, You will be able to invest money, which will be credited as cash in your account and the premium by the end of 11th month, will be provided to you with a month bonus.',
  flexip2: 'The current gold cost on the day of purchase will be taken into account when we buy gold with this gold scheme. The gold you purchase will be subject to gold making and wastage charge*.',
  flexip3: 'Note: Under this scheme, you won\'t be able to withdraw the premium as cash, the money which is available in your account only be used to buy gold based on that particular day gold rate',
  downloadhere: 'Download Brochure',
  happyGoldHead: 'HAPPY GOLD SCHEME',
  happyGold1: 'With this scheme, Your money will be invested at the current gold rate and will be accumlated as gold weight rather than cash in your account. ',
  happyGold2: 'By the end of the 11th month, you will be able to buy gold corresponding to the accumulated weight without any making and wastage charges*.',
  happyGold3: '*- Taxes Apply at 3% ',
  termshead: 'Terms and Conditions',
  termsbody1: 'The premium due amount can be paid on any day of the month.',
  termsbody2: 'The savings tenure is 11 months only.',
  termsbody3: 'The premium amount can also be paid through NEFT ( Bank account details are given below )',
  termsbody4: 'while depositing the premium amount though NEFT , do not forget to mention the customer identification number as well as the name of the customer with whom the gold scheme is registered.',
  termsbody5: 'After depositing the amount through bank , kinldy call our customer call number and inform them regarding the transfer.',
  termsbody6: 'The gold scheme once registered is not transferable and the entire gold scheme package cannot be transfered to the other person.',
  termsbody7: 'The gold scheme cannot be closed before the tenure. kinldy bring the gold scheme card while depositing the premium amount directly through cash.',
  termsbody8: 'The premium due amount can be paid on any day of the month. kindly bring the customer registration card when buying the gold corresponding to the premium amount After the tenure completes.',
  termsbody9: 'All the " Happy Gold " customers will be able to buy the gold coressponding to the premium amount with any gold making and wastage charge.',
  termsbody10: 'Taxes Application ( Current GST 3 % ).',
  termsbody11: ' The store has the full privilege to modify / change the above terms and conditions.',
  locations:'locations',
  storename1: 'Sri Balagopalan Jewellery Mart',
  storename2: 'Sri Silver',
  goldstore: 'Gold Store',
  address: 'Address',
  addressbody1: `No.2, Jansi Rani Complex ,\n YMCA Building Opposite, Madurai – 625 001.`,
  buisnesshours: 'Buisness Hours',
  buisnesshoursbody1: 'Every Day 9AM - 9PM',
  phonenumber: 'Phone Number',
  phonenumberbody1: '+91-99949-26518',
  phonebody1: '9994926518',
  phonenumberbody2: '+91-452-2346518',
  silverstore: 'Exclusive Store for Silver',
  addressbody2: '218, West Masi Street Madurai-625001',
  phonenumberbody3: '+91-95854-42214',
  phonenumberbody4: '0452-4393919',
  get: 'Get',
  intouch: 'in touch',
  fullname: 'Full Name',
  email: 'Email',
  subject: 'Subject',
  message: 'Message',
  enter: 'Enter Your ',
  send: 'Send ',
  connect: 'Connect',
  withus: 'with us',
  allcollections:'All Collections',
  marriage: 'wedding',
  story: 'story',
  
  aboutusdata1: 'Sri balagopalan jewelry mart (SBJ) one of the finest sellers of gold,silver and diamond in and around Madurai. It was first inagurated by S.B.Senthil Kumar in 1992 as a small scale industry with 2 employees , the customers satisfaction on the quality of the products and services made our enterprise the best place to buy jewelry was primary key for increase in ratio in the family having around 30 employees till date.The small scale was then made as the large scale jewelers around 2012 which has become the landmark for purchasing the exquisite ornaments . The uniqueness of our enterprise is that the jewelry will be carved based on the customers design and our collection is said to have an tranditional essence as our goldsmiths have experience more than 20 years.',
  aboutusdata21: 'The major intresting feature of our enterprise is the jewellery will be delivered to the customers on-demand brings the exact model without even missing the minute detailing in the jewellery which has attracted the customers even to the rural areas in and around madurai, our organization deals with the B2C having large number of collections to choose for each and every model which fits the customers taste.',
  aboutusdata22:'The promises of our enterprise includes:',
  aboutusdata23:'our enterprise only uses 916 Hallmark gold for making any kind of jewellery',
  aboutusdata24:'Every details are transperant to the customers.',
  aboutusdata25:'The Diamonds used in jewellery are approved and certified.',
  aboutusdata26:'The Purchase of gold for the enterprise are properly maintained',
  aboutusdata3: 'Our enterprise instituted a number of savings schemes to suit the specific needs of various demographics, distinguishing itself a great deal from the run-of-the-mill business practices in retail jewellery and has the collections has been distinguished specific to the events.',
  aboutusdata4:'The "Sri Silver" exclusive showroom for the silver  the overwhelming response and love of the people made us in introducing the showroom which has the distinguished collections of silver ornaments on the latest trend for all occasions ,auspicious events.',

  engal:'our',

  // aboutusdata1:'In 1992, Sri Balagopalan Jewellery Mart has been inaugrated in Small Scale by S.B.Senthilkumar . Each and everyone feel elite on shopping with us in quality, design, price and service . Quality for the end consumer is key priority for us and we are comitted to fulfill our promises!!!',
  Gold: 'gold',
  Golda: 'gold',
  Diamond:'diamond',
  Diamonda: 'diamond',
  Silver: 'silver',
  Silvera: 'silver',
  talktoushome: 'Have questions about our exquisite jewellery collections and can\'t decide what suits your taste! Look no further',
  talktousgold: 'Confused with the gold collection you are looking at? Leave it to us',
  talktousdiamond: 'Confused with the Diamond collection you are looking at? Leave it to us',
  talktoussilver: 'Confused with the Silver collection you are looking at? Leave it to us',
  talktousproduct: 'Can\'t decide between our products? We\'ll make sure that is not a problem, reach out to us',
  talktouscollection: 'Not convinced of our displayed collection here? This is just a tip of iceberg with our collections available at our store, contact us for more info ',
  talktousgoldscheme: ' Not planning to buy gold yet? Invest in our gold scheme to make the most out of your saving. ',
  promise1: 'Certified Pure Gold',
  promise2: 'All Jewels are brand new',
  promise3: 'Transparency in pricing',
  promise4:'Secure Gold Scheme',
 

  dollar: 'dollar',
  anklet: 'anklet',
  noproductsfound: 'No Products Found',
  fillallfields: 'Please fill all the fields',
  close: 'close',


  silvervessels: 'Vessels',
  idols:'idols',
  poojaitems: 'Pooja Items',
  
  // goldheroline1: 'Get ready to explore the wide spectrum of',  
  goldheroline1:'Explore Our latest',
  goldheroline2: 'Gold ORNAMENTS',
  goldheroline3:'that',
  goldheroline4:'enhances the grace and beauty',
  // goldheroline5:'beauty',
  
  diamondheroline1:  'Enhance your beauty by ',
  diamondheroline2: 'Wearing our ',
  diamondheroline3: 'Diamond',
  diamondheroline4: 'Ornaments',
  diamondheroline5:'',
  diamondheroline6:'',

  
  silverheroline1: 'Explore our dazling ',
  silverheroline2: 'Silver Ornaments',
  silverheroline3:'',



  collectionsheroline1: 'Let our Jewels make your ',
  collectionsheroline2:  'life bright and shine with ',
  collectionsheroline3:  'Exquisite Collections', 



  fullnameerror: 'Full Name should be atleast 3 letters',



  phoneerror: 'Enter valid 10 digit numbers',
  emailerror: 'Enter valid Emailaddress',
  subjecterror: 'Subject Should be ateast 3 letters',
  messageerror:'Message should be atleast 10 letters',
  viewourjewels: 'View Our Jewels',
  goldjewels: 'Gold Jewels',
  silverjewels: 'Silver Jewels',
  diamondjewels: 'Diamond Jewels',

  comments1: 'This is such a beautiful statement necklace. I felt like showing it off the whole day I wore it. I received multiple compliments the ENTIRE day ? It was my first time wearing a necklace this large, but it’s too beautiful and made too well to resist. I received the order very quickly as well. I’ll be back VERY soon!',
  comments2:'SBJ\'s new collection and so relevant especially with everything happening today. So many exquisite pieces full of colour and life, it can make anyone smile.',
  comments3:'The workmanship is exquisite and designs are unique. Extremely happy with every purchase I have made so far',
  comments4:'I’ve had my ring for 14 years and it’s still so pretty. I do have it checked and flashed every year or so. It is light and comfortable. SBJ did an incredible job creating wedding Rings to match. I get loads of compliments. ',
  

  username1: 'Akilesh',
  username2: 'Sharmila',
  username3: 'Ramji Dev',
  username4: 'Menaka Ramalingam',
  
  userprofession1: 'Buisness Man',
  userprofession2: 'Software Engineer',
  userprofession3: 'LIC Agent',
  userprofession4: 'Home Maker',
  enquire:'Enquire',
  
}